### ISSUE TITLE
sqlite3.ProgrammingError: Incorrect number of bindings supplied

### ISSUE THREAD

**Issue by juliarizza** [juliarizza/certificate_generator#14]
When trying to add or remove some users from the certificates list, rises this error.

```
Traceback (most recent call last):
  File "/home/julia/gerador_cert/controllers/certificates.py", line 195, in remove_client
    str(subscription_id)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 2 supplied.
Traceback (most recent call last):
  File "/home/julia/gerador_cert/controllers/certificates.py", line 195, in remove_client
    str(subscription_id)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 2 supplied.
```

**Comment by juliarizza** [comment]
Fixed on f1a8084f1513df0a8aab159fabbe35788cf54643
